### ISSUE TITLE
[SimC] Assassination 7.2.5 APL Review

### ISSUE THREAD

**Issue by aethys256** [Ravenholdt-TC/Issues#1]

**Comment by Mystler** [comment]
Exsanguinate and Garrote APL Improvements by Miie: https://pastebin.com/pZyt3QFV

**Comment by Mystler** [comment]
Slightly changed and pushed Miie's APL changes. This will push Exsanguinate builds a fair bit. 👍 
See simulationcraft/simc@eb7e518e6f022b5812b837d41d70f758d2c66707.

**Comment by omeomorfismo** [comment]
i hope this isnt the wrong thread but changing to prologed power seems to be a gain of ~10k dps
