### ISSUE TITLE
[Bugs] Shadow Satyr's Walk extra energy refund

### ISSUE THREAD

**Issue by aethys256** [Ravenholdt-TC/Issues#14]
**Game Version:**
>7.2.5 Live Build 24330

**Description:**
>SSW's effect ignores the target hitbox, giving more energy refund.

**Reproduce rate:**
>High

**Details:**
>Considering it takes the row distance (center of the target - center of the player) for the effect computation, you can get 3 + 3 energy instead of 1 + 3 energy.

**Howto:**
>Stay at the max range.

**Comment by Mystler** [comment]
Closing for this for BfA.
