### ISSUE TITLE
[Bugs] Combat Potency uses normalization for Off-hand white attacks

### ISSUE THREAD

**Issue by Lorentz21** [Ravenholdt-TC/Issues#20]
Intended or not, it works like it did before.
For white attacks chance is ( 30% + 2% * Fortune_Strikes_ranks ) * weapon_speed / 1.4
For Main gauche it's usual 30% + 2% * Fortune_Strikes_ranks

**Comment by Mystler** [comment]
Added it back to SimC in simulationcraft/simc@eca0dac46b7258e3502362ae7955c79497bfefda.

**Comment by Mystler** [comment]
Closing for this for BfA. Potency has been adjusted and has a new and intended normalization formula.
