### ISSUE TITLE
[SimC] Implement DfA + Dark Shadow Dance Stacking

### ISSUE THREAD

**Issue by Mystler** [Ravenholdt-TC/Issues#21]
You can now use Shadow Dance with Dark Shadow mid-air during Death from Above and thus get a buffed buffed Eviscerate.

**Comment by aethys256** [comment]
Added in https://github.com/simulationcraft/simc/commit/03e4bd795c3864ab5160252860b15f76e9b68c9c and https://github.com/simulationcraft/simc/commit/a80c0e9574c619b9f7a88467f04fcabe2775fd80 :)
