### ISSUE TITLE
[SimC] Update T20 default profiles

### ISSUE THREAD

**Issue by Mystler** [Ravenholdt-TC/Issues#24]
Some NH trinkets still seem so good that we'd want them in the ToS profiles, even if they have much lower item levels.

**Comment by aethys256** [comment]
Done in https://github.com/simulationcraft/simc/commit/a89d0a21f1773f8121d79ad3b249777b571ea626

**Comment by aethys256** [comment]
Adjusted in https://github.com/simulationcraft/simc/commit/032c141fadd8fba53c28ded9b5ed38a893ab5c6e and in https://github.com/simulationcraft/simc/commit/3b556c855321eb1ba5c73d3bc1bdf7ce562e4270
