### ISSUE TITLE
[Bugs] WM and DfA

### ISSUE THREAD

**Issue by aethys256** [Ravenholdt-TC/Issues#25]
**Game Version:**
>7.2.5 Live Build 24330

**Description:**
>Weaponmaster procs bugs out DfA behavior.

**Reproduce rate:**
>100%

**Details:**
>What happens is that WM procs cancels the next ability queued in your DfA.
If your DfA hit procs weaponmaster (that scales on the # of targets), then it will cancel the Eviscerate.
Here is two example, in ST and in AoE:
![wm_dfa_st_bug](https://cdn.discordapp.com/attachments/321995036193456149/325906320370827264/unknown.png)
![wm_dfa_aoe_bug](https://cdn.discordapp.com/attachments/244072792948080641/325926470813745154/unknown.png).

>Although, if WM procs on the Eviscerate, the behavior is the same as a normal Eviscerate.
![wm_dfa_evisc](https://cdn.discordapp.com/attachments/321995036193456149/325907980774014977/unknown.png)

**Howto:**
>WM and DfA talented.

**Comment by aethys256** [comment]
Implemented in https://github.com/simulationcraft/simc/commit/343f912f5f5c305576e897073866291fb549c791

**Comment by aethys256** [comment]
In fact, it's a range issue for the DfA hit.
The bug is only if WM procs on DfA, then it 100% cancel the Evisc.
Will edit above.

**Comment by aethys256** [comment]
Reimplemented in https://github.com/simulationcraft/simc/commit/99213834338af38a912b009a17ea6108a653e847

**Comment by pjeannet** [comment]
Do you know if this has been reported to blizzard yet? 
It saved me a headache of understanding why me DfA did not hit xD

**Comment by Mystler** [comment]
Just want to note that I was trying to reproduce this on 7.3 PTR and I couldn't. I think WM procs for the DfA pulse are simply disabled on PTR, but I may just have been really "unlucky" and would like some confirmation.

**Comment by Aethys256** [comment]
It is fixed, thanks Blizzard 👍 

![image](https://user-images.githubusercontent.com/10969743/29996083-3605cd58-8ff8-11e7-87dc-87e2192257f0.png)

Fixed in simc in https://github.com/simulationcraft/simc/commit/9271773fb21b62b895b8de9bbdc394229e28cb99 :)

**Comment by aethys256** [comment]
It seems to be fixed in 7.3, thanks Blizzard 👍 

![image](https://user-images.githubusercontent.com/10969743/29996128-2112e65a-8ff9-11e7-95a8-990619da4967.png)

Fixed in simc in https://github.com/simulationcraft/simc/commit/9271773fb21b62b895b8de9bbdc394229e28cb99 aswell.
