### ISSUE TITLE
[Bugs] Second Shuriken does not proc

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#26]
**Game Version:**
>7.2.5 Live Build 24330

**Description:**
>Second Shuriken doesn't proc from Shuriken Storm

**Reproduce rate:**
>100%

**Details:**
>Is very likely a Bug. Switching T1 Talents doesn't change the behavior.

**Howto:**
>Spam Shuriken Storm for a while and watch for procs (~10 mins was my example size).

**Comment by Mystler** [comment]
This has been fixed in the latest hotfix.
