### ISSUE TITLE
[SimC] (sub) Nightstalker Snapshotting

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#27]
**Description:**
> Nightstalker snapshots Nightblade with Vanish/Shadow Dance/Stealth.
>![Details](http://i.imgur.com/RW6oDgc.png)

**Comment by aethys256** [comment]
Isn't anymore the case ? Didn't checked

**Comment by Mystler** [comment]
Nightstalker is correctly applied to all abilities in Simc. Closing this again. (Sorry, it was obviously too late when I checked last night.)
