### ISSUE TITLE
[APL] Opening Shadow Dance with Eviscerate?

### ISSUE THREAD

**Issue by Wunjuh** [Ravenholdt-TC/Issues#28]
Has this been simmed? I´m doing this in game atm with Shd+evis macro, so build 5+ cps, press macro, can use 2 finishers inside dance like that, this should be a gain over 2 SS + finisher

**Comment by Mystler** [comment]
I think this was already discussed a few days ago on the class discord. Going into dance with 5+ CP is a loss.
