### ISSUE TITLE
[SimC] Subtlety 7.2.5 APL Review

### ISSUE THREAD

**Issue by aethys256** [Ravenholdt-TC/Issues#3]

**Comment by aethys256** [comment]
https://github.com/Ravenholdt-TC/Rogue/issues/9
https://github.com/Ravenholdt-TC/Rogue/issues/21
https://github.com/Ravenholdt-TC/Rogue/issues/13
>Improve ShD usage with DSh overall and DSh + DfA

**Comment by Lorentz21** [comment]
Minor improvement - if we have Goremaw's Bite up or Feeding Frenzy buff up loosen energy requirement to use stealth_cds.
Changing line
> actions.stealth_als=call_action_list,name=stealth_cds,if=energy.deficit<=variable.stealth_threshold&(!equipped.shadow_satyrs_walk|cooldown.shadow_dance.charges_fractional>=variable.shd_fractional|energy.deficit>=10)

to 

>actions.stealth_als=call_action_list,name=stealth_cds,if=energy.deficit<=variable.stealth_threshold-25*(!cooldown.goremaws_bite.up&!buff.feeding_frenzy.up)&(!equipped.shadow_satyrs_walk|cooldown.shadow_dance.charges_fractional>=variable.shd_fractional|energy.deficit>=10)

yields approximately 7k DPS gain for default T20 heroic profile
https://www.raidbots.com/reports/ByeM_kov7Z/index.html - report link

**Comment by mrdmnd** [comment]
Have we considered energy-dumping prior to the Symbols or Goremaw coming off CD?

I.e. you know Symbols is going to be off CD in 1, 2, 3, or 4 GCDs, so we dump energy appropriately such that the energy we get from it does not overcap us? Might net a few extra backstabs or something.

**Comment by aethys256** [comment]
New DfA Subtlety APL:
https://github.com/simulationcraft/simc/commit/80f445852e8cffb5710461d6b37ec5999542fa38
