### ISSUE TITLE
[Bugs] Stealth DfA disconnect

### ISSUE THREAD

**Issue by Faildoll** [Ravenholdt-TC/Issues#31]
**Game Version:**
>7.2.5 Live Build 24415

**Description:**
> DfA out of Stealth causes a disconnect.

**Reproduce rate:**
> 100%

**Details:**
> when you stealth and use DfA you get a disconnect / game stops entirely. I encountered this in Arcway and just did it again in the Orderhall.

**Howto:**
> Get Combopoints -> Stealth -> DfA

**Comment by aethys256** [comment]
Confirmed, happened to me 2 times in mythic dungeons.

**Comment by Faildoll** [comment]
It also happens when you do Shadowmeld -> DfA

**Comment by Faulty** [comment]
Tested on July 7 and getting no disconnects. Build 24461
