### ISSUE TITLE
[simc] APL Trinket usage added/adjustment

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#32]
Those conditions where a win over current implementation.
Tested with Rogue_Subtlety_Dark_T20M profile.

specter:
>actions.cds+=/use_item,name=specter_of_betrayal,if=buff.shadow_dance.up&((buff.symbols_of_death.up)|(buff.vanish.up|cooldown.vanish.remains>=45))

moonglaives:
>actions.cds+=/use_item,name=umbral_moonglaives,if=buff.symbols_of_death.up&((buff.shadow_dance.up)|(buff.vanish.up))

**Comment by aethys256** [comment]
Implemented in https://github.com/simulationcraft/simc/commit/80f445852e8cffb5710461d6b37ec5999542fa38
