### ISSUE TITLE
[Bugs] DfA allows Off GCD Mid-Air

### ISSUE THREAD

**Issue by aethys256** [Ravenholdt-TC/Issues#33]
**Game Version:**
>Live 7.2.5.24430

**Description:**
>DfA allows Off GCD Mid-Air

**Reproduce rate:**
>100%

**Details:**
>The buff Death from Above is 1s duration, but the execute time of DfA is 1.5s (the Eviscerate come 500ms after the buff fades). It means you can use any off gcd spell (i.e. % dmg modifier) during this window. It's likely a bug since you shouldn't be allowed to use spells during the animation of another spell. (It's as -hacky- as DH cancel animations in 7.0)
There is multiple compensation of this bugfix possible like make the evisc when the buff ends for example (so the total execute time of DfA would be 1s and not 1.5s).
Altough, I guess the GCD should stay at 2s.

**Howto:**
>Spam your off-gcd while in the air, they'll be queued for the 500ms "gcd free" window.

**Comment by Mystler** [comment]
DfA is gone. RIP. Closing for this for BfA.
