### ISSUE TITLE
[APL] Outlaw specter usage

### ISSUE THREAD

**Issue by Saberslashh** [Ravenholdt-TC/Issues#34]
Those conditions were a win over current implementation.
Tested with Rogue_Outlaw_T20M profile and personnal gear.
Benefits more from MfD+Haste builds.

`actions.cds+=/use_item,name=specter_of_betrayal,if=(mantle_duration>0|buff.curse_of_the_dreadblades.up|(cooldown.vanish.remains>11&cooldown.curse_of_the_dreadblades.remains>11))`

**Comment by Mystler** [comment]
Thank you. Implemented in simulationcraft/simc@0727f3c560ef312fd11742a09f0ff180938fcc2a.
