### ISSUE TITLE
[APL] Subtlety ToS Trinket update/implementation

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#38]
**Description:**
 Updated/implemented some trinkets

**specter of betrayal**
>removed 2 unnneded conditions
>`actions.cds+=/use_item,name=specter_of_betrayal,if=talent.dark_shadow.enabled&buff.shadow_dance.up&(buff.symbols_of_death.up|(!talent.death_from_above.enabled&((mantle_duration>=3|!equipped.mantle_of_the_master_assassin)|cooldown.vanish.remains>=43)))`

**tarnished sentinel medallion**
>`actions.cds+=/use_item,name=tarnished_sentinel_medallion,if=talent.dark_shadow.enabled&buff.shadow_dance.up&(buff.symbols_of_death.up|(!talent.death_from_above.enabled&((mantle_duration>=3|!equipped.mantle_of_the_master_assassin)|cooldown.vanish.remains>=50)))`

**tome of unraveling sanity**
> use it so you get the crit buff during symbols
>`actions.cds+=/use_item,name=tome_of_unraveling_sanity,if=cooldown.symbols_of_death.remains<=12|(!stealthed.all&!buff.vanish.up&time<=10)`

**vial of ceaseless toxins**
>`actions.cds+=/use_item,name=vial_of_ceaseless_toxins,if=talent.dark_shadow.enabled&buff.shadow_dance.up&(buff.symbols_of_death.up|(!talent.death_from_above.enabled&((mantle_duration>=3|!equipped.mantle_of_the_master_assassin)|cooldown.vanish.remains>=60)))`

**leviathans hunger**
>line it up with vanish
>`actions.cds+=/use_item,name=leviathans_hunger,if=cooldown.vanish.remains<=2`

**Comment by Mystler** [comment]
Added some of those in simulationcraft/simc@c0b485f3495b487138bb38ea990c8c265f6cfb32.
Medallion and Hunger were neutral or a loss compared to the default condition and since they are not on the rogue loot table and subject to nerfs, I don't think we have to optimize those further.
