### ISSUE TITLE
[APL] Nightblade condition update

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#39]
**Description:**
> better T19 support and higher Time_to_die becouse of NB changes

old:
>`actions.finish+=/nightblade,cycle_targets=1,if=!talent.death_from_above.enabled&(!talent.dark_shadow.enabled|!buff.shadow_dance.up)&target.time_to_die-remains>8&mantle_duration=0&((refreshable&(!finality|buff.finality_nightblade.up))|remains<tick_time*2)
`
new:
>`actions.finish+=/nightblade,cycle_targets=1,if=(!talent.death_from_above.enabled|set_bonus.tier19_2pc)&(!talent.dark_shadow.enabled|!buff.shadow_dance.up)&target.time_to_die-remains>12&mantle_duration=0&((refreshable&(!finality|buff.finality_nightblade.up))|remains<tick_time*2)`

**Comment by Mystler** [comment]
Thank you. Implemented in simulationcraft/simc@f38bdb91a19be90365d9f3cdc2489f37a5b46a7c.
