### ISSUE TITLE
[Bugs] Unbreakable Vanish

### ISSUE THREAD

**Issue by aethys256** [Ravenholdt-TC/Issues#4]
**Game Version:**
>7.2.5 PTR Build 24271

**Description:**
>Vanish does not break when using certain abilities.

**Reproduce rate:**
>Works every time

**Details:**
>- (All) animation length seems to play a role
>- (Asn) bonus from nightstalker only applies to first ability
>- (Sub) bonus from nightstalker applies to both abilities

**Howto:**
>Works best with a macro:
>>/cast vanish
/cast ability
/stopattack

This video explains it as well: https://www.youtube.com/watch?v=p6ORoH4YuX8

**Comment by Mystler** [comment]
Looks like this went live as well.

**Comment by fuu1** [comment]
besides first thought, it works with all abilities.
if you want to reproduce it with abilities with long animations create a macro and spam it.
if you want to line up different abilities you can use a cast sequence.

**Comment by leovdw** [comment]
Still in the game ?

**Comment by Mystler** [comment]
I added a simple implementation of the Vanish bug in simulationcraft/simc@1b30ed6eb14e54b818bc40f4d1bd1de159a65330. Now Blizzard can fix it, thanks.

**Comment by fuu1** [comment]
the bug is fixed, i was not able to recreate it in multiple tryes as well as other TC's.

**Comment by aethys256** [comment]
Fixed in 7.3, thanks Blizzard 👍 

Fixed in simc in https://github.com/simulationcraft/simc/commit/9230fc81b61d6a34d72242edd9f24df0a77e9018
