### ISSUE TITLE
[APL] Specter condition improvement/change, Shadow Dance condition change

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#42]
**Specter:**
> alignment changes to use it more often
> targeted on t19/20 combinations without t20 4p

**Shadow Dance:**
>disabled one condition in dark build (may need some research)

**APL diff:** [changes](https://www.diffchecker.com/Lc9b7Ps3)

**Comment by Mystler** [comment]
Thank you. Specter condition change implemented in simulationcraft/simc@591edcf3f4ba011a090cc694e6bb927ab4e4058f. Shadow Dance condition was improved in a different way.
