### ISSUE TITLE
[APL] Vanish condition update

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#43]
**Vanish Condition**
>Updated Vanish condition to better align with dfa/dance
>
>**APL diff:** [changes](https://www.diffchecker.com/0GHEsRhj)

Update: reworked, should be fine now.
Update - 2: lowered energy pooling value (win for t20, neutral for t19)

**Comment by Mystler** [comment]
Thank you. Implemented in simulationcraft/simc@ec651d40fe11a1fc588f936fd0701e91a2812e6a.
