### ISSUE TITLE
[APL] Toxic Blade is not synced with Vanish

### ISSUE THREAD

**Issue by Notter** [Ravenholdt-TC/Issues#44]
Sim report:
https://www.raidbots.com/reports/jA8dHe4aGbBVGfzxrV7zk/index.html

Abilities Used:
3:53 - Toxic Blade
4:01 - Vendetta
4:07 - Kingsbane
4:09 - Vanish
--------------------------------------
Toxic blade off cooldown at 4:18
The next Toxic Blade is only at 4:23

Vanish's mantle buff, was not synced with Toxic Blade debuff.

I believe that in such a case, it's worth to even miss one TB cast, and hold it for vanish.
otherwise, vanish should have been delayed by 9 seconds.

**Comment by Mystler** [comment]
I have run a bunch of tests and every attempt to delay TB or Vanish turned out to be a loss. 😐
