### ISSUE TITLE
[SimC] Poison Bomb deals an extra tick of damage

### ISSUE THREAD

**Issue by Notter** [Ravenholdt-TC/Issues#46]
SimC is having Poison Bomb tick on-hit - making it tick 7 times per proc.
It only ticks 6 times per proc in-game because it doesn't tick on-hit.

![pb](https://user-images.githubusercontent.com/16865410/28248939-c64717c8-6a55-11e7-83d2-3e6a9d74ceeb.png)

**Comment by Mystler** [comment]
Thanks for the report. Changed in simulationcraft/simc@4edb79142d117209e29d0544ec54d60707e1caa9.
