### ISSUE TITLE
[SimC] Kingsbane hits shouldn't proc Deadly Poison

### ISSUE THREAD

**Issue by Notter** [Ravenholdt-TC/Issues#47]
SimC is applying deadly poison from kingsbane MH/OH hits. 
That doesn't happen in-game, You get a stack of the damage increase debuff from the initial hits, but they can't actually proc a deadly poison hit.

**Comment by Mystler** [comment]
Fixed in simulationcraft/simc@ad7afcbc293dffb442b68e6943100d36c04f4c17.
