### ISSUE TITLE
[APL] [Outlaw] Umbral Moonglaive improvement 

### ISSUE THREAD

**Issue by Saberslashh** [Ravenholdt-TC/Issues#48]
The APL should be using vanish 3 seconds after the trinket's usage to make maximum damage output.
You should save 1 vanish out of 3 for it most likely as saving vanish for it isnt worth it due to RB/TB.

**Comment by Notter** [comment]
Make sure to change it to 3 seconds before vanish (for all specs)

**Comment by Mystler** [comment]
Closing for this for BfA.
