### ISSUE TITLE
[APL] Trinkets are not used on Cooldown for Assassination

### ISSUE THREAD

**Issue by Notter** [Ravenholdt-TC/Issues#49]
I've noticed that in the span of 300 seconds, Specter of Betrayal is used only 6 times, while it should have been used 7 times.
This trinket does not benefit from anything assassination can do, and should be used on Cooldown.

right now the APL tries to sync it with vendetta.
This might also devalue this trinket in the trinkets ranking list.

Current APL:
> use_item,name=specter_of_betrayal,if=buff.bloodlust.react|target.time_to_die<=20|debuff.vendetta.up

SimC by default sync every on-use trinket with Vendetta.
It might be better to make it so the default would be to use on cooldown, and only optimizations would try to align it with other abilities.
This might be a reason why the trinket ranking list is skewed in favor of passive trinkets.

**Comment by aethys256** [comment]
Fixed in https://github.com/simulationcraft/simc/commit/f5fbf2947aec4dca1b5b835fd2852836bd9f8329
