### ISSUE TITLE
[Results] Trinket List

### ISSUE THREAD

**Issue by aethys256** [Ravenholdt-TC/Issues#5]
Checklist (added by Mystler):
- [x] Assassination T19M_NH
- [x] Outlaw T19M_NH
- [x] Subtlety T19M_NH
- [x] Assassination T20H
- [x] Outlaw T20H
- [x] Subtlety T20H

**Comment by Mystler** [comment]
Planning to add T19M_NH and T20H trinket sims for all specs with their best looking build. Trinket levels will be 900-955. Maybe other combinations after that?

**Comment by aethys256** [comment]
We can close this, it's on the website.
