### ISSUE TITLE
[APL] Subtlety Nightblade Condition

### ISSUE THREAD

**Issue by 13a5ti** [Ravenholdt-TC/Issues#51]
Only using Nightblade outside of Symbols of Death and removing the Nightblade Finality condition seems to be a DPS increase for both DfA profiles (+10k to 12k) and DPS neutral for both MfD profiles.

`actions.finish=nightblade,if=(!talent.dark_shadow.enabled|!buff.shadow_dance.up)&target.time_to_die-remains>6&(mantle_duration=0|remains<=mantle_duration)&((refreshable)|remains<tick_time*2)&!buff.symbols_of_death.up
`

**Comment by Mystler** [comment]
This is a very specific change. I implemented it a bit differently in simulationcraft/simc@5e49a4dfec575e339ed57c56c0e61d48c1d6b13a. Thank you!
