### ISSUE TITLE
[APL] Nigthblade conditon update

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#53]
**Nightblade:**
>change the condition to refresh NB so you don't need to refresh it during symbols.
>mainly a win for DfA
>
>**APL diff:** [changes](https://www.diffchecker.com/a7n69ZQr)
> Note: didnt check with T19.

**Comment by Mystler** [comment]
Thanks. Implemented in simulationcraft/simc@b38e9048010888686ebb47cd2eb2a247e3aa5722.
