### ISSUE TITLE
[SimC] Goremaw's Bite not affected by Shadow Blades

### ISSUE THREAD

**Issue by 13a5ti** [Ravenholdt-TC/Issues#54]
Goremaw's Bite always awards 3 CPs regardless of the Shadow Blades buff.
As seen in the following report at 0:17.323, 3:38.347 and 4:40.218

[https://www.raidbots.com/reports/5fHcbGLHHnqfKvHtM9ALfx/index.html](https://www.raidbots.com/reports/5fHcbGLHHnqfKvHtM9ALfx/index.html)

It should award 4 CPs when the player is buffed by Shadow Blades.

**Comment by aethys256** [comment]
I don't get the issue, it's awarding 3cp as it should be.
Altough, we might add this one in the bug report (fact that SBlades doesn't affect it).

**Comment by aethys256** [comment]
Nevermind the comment above, I didn't know the bug was fixed.
Will fix it soonTM (this week-end) if @Mystler didn't do it before.

**Comment by Mystler** [comment]
Thanks for the report. Fixed in simulationcraft/simc@27a62d224e4afc7fd8a2fb782e1e270cbc260cf8.
