### ISSUE TITLE
[APL] Vanish bug update for DfA

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#55]
**Vanish condition:**
> updated the condition to abuse the bug more efficient
> it should use vanish-ss(-ss) more often.
>
>**APL diff:** [changes](https://www.diffchecker.com/tofplye6)

**Comment by Mystler** [comment]
Thanks! Added in simulationcraft/simc@6fcda105e5759ed38dfe015288f1336d6407eedd.
