### ISSUE TITLE
[SimC] Test which abilities are buffed by Surge of Toxins

### ISSUE THREAD

**Issue by Notter** [Ravenholdt-TC/Issues#59]
The spell data for the passive ability Surge of Toxins, might be inaccurate
It mentioned these following abilities:

> Affected Spells: Deadly Poison (2818), Deadly Poison (2823), Wound Poison (8679), Wound Poison (8680), Venomhide Poison (14795), Spore Cloud (32643), Deadly Poison (113780), Agonizing Poison (200803)

Yet, in a test done by Swol, he found the following:

- Poison Bomb is buffed

- Kingsbane DoT is buffed

- Kingsbane MH/OH hits are **not** buffed

**Comment by Mystler** [comment]
**Edited:** Poison Bomb and Kingsbane DoT were already handled correctly. I applied a fix to simc, so that KB strikes are not affected. This should now sim correctly.
