### ISSUE TITLE
[APL] First of the Dead improvement

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#60]
**Condition changes for first of the dead:**
> updated the condition to get better use of the Legendary effect
>
>**APL diff:** [changes](https://www.diffchecker.com/VIzvxE4h)
>
> Edit: is also a win for dfa (but only in st)

**Comment by fuu1** [comment]
**some additional improvements:**
> 1. Using a finisher pre symbols is a damage win (for DfA)
> 2. Updated shuriken storm condition to use bs/sstrike with 2 targets during the buff window (was a loss on 3 targets)
>
>**APL diff:** [changes](https://www.diffchecker.com/Zv6KlYKs)

**Comment by fuu1** [comment]
**some additional improvements for non Dfa:**
> finish with 5+ cp instead of 6 while fist buff is up and shb is not running
>
>**APL diff:** [changes](https://www.diffchecker.com/aHzQ07GH)

**simulation**
>simulation result: [report](https://www.raidbots.com/simbot/report/4QmSXKvuYaS9226HsE5FaP)

![sim](https://media.discordapp.net/attachments/321995036193456149/345896127456870401/Unbenannt.png?width=441&height=80)

**Comment by Mystler** [comment]
Modified and implemented in https://github.com/simulationcraft/simc/commit/478ce38c651825ac1655e3061621610988189175.
