### ISSUE TITLE
[APL] Nightblade Condition improvement

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#61]
**Condition changes for Nightblade**
> Refresh NB earlier (more aggressive) to covers the symbols window
>
>**APL diff:** [changes](https://www.diffchecker.com/R4tc1hx6)

**Simulation:**
>**simulation results:** [report](https://www.raidbots.com/simbot/report/c7M2GVzaSrV8FaPKvn16YL)
>
![sim results](http://i.imgur.com/QOfZUkx.png)

**Comment by Mystler** [comment]
Thanks! Added in https://github.com/simulationcraft/simc/commit/abf83eb6efa790b329ae81016b81def3bb9bb212.
