### ISSUE TITLE
[APL] Subterfuge fix for DfA

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#62]
**Condition changes for Subterfuge:**
> Dfa interaction was broken with subterfuge (didn't trigger ShD after DfA under certain conditions)
>
>**APL diff:** [changes](https://www.diffchecker.com/WOy7FLhO)

**Simulation**
>Simulation result: [report](https://www.raidbots.com/simbot/report/vjuHqQB9exn5QusXW8eWTA)

![sim](https://media.discordapp.net/attachments/321995036193456149/345973838040793089/Unbenannt.png)

**Comment by Mystler** [comment]
Implemented in https://github.com/simulationcraft/simc/commit/bb84ac219c62dbad506bb34579efa122239f318f.
