### ISSUE TITLE
[Bug] First of the Death buff application

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#63]
**Game Version:**
> 7.2.5 Live Build 24740

**Description:**
> First of the death buff applies slightly deleyed

**Reproduce rate:**
> 100%

**Details:**
>First of the death buff gets applied slightly delayed what leads to CP loss when we use symbols-combo builder in a macro. It **doesn't** let us Ability-Ability-Combo Builder(with First of the Dead buff) but makes it possible to Symbols-Death from Above-Combo Builder(with First of the Dead buff)

**Howto:**
>If you use this macro you wont get the benefit from First of the Death on the Backstab cast
>`/cast Symbols of Death
/cast Backstab`

**Comment by Mystler** [comment]
Closing for this for BfA.
