### ISSUE TITLE
[APL] minor improvements for AoE

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#64]
**Condition changes for AoE:**
> Play around Finality Eviscerate during aoe situations is a overall damage win 
>
>**APL diff:** [changes](https://www.diffchecker.com/shbDqBMy)

**Simulation**
>Simulation result: [report](https://www.raidbots.com/reports/kCdUfvqAV5CmwAXcy2mReD/index.html)

![sim](https://media.discordapp.net/attachments/317311523196370954/346407328385466369/Unbenannt.png)

**Comment by Mystler** [comment]
Implemented in https://github.com/simulationcraft/simc/commit/da30580672bc4705af4796922e0594beb49bd5ac.
