### ISSUE TITLE
[APL] First of the dead improvements for Anticipation

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#65]
**Improvements for Anticipation:**
> Use the buff  more efficiently with anticipation(symbols-bs-bs-dfa)
>
>**APL diff:** [changes](https://www.diffchecker.com/LyjQj6FK)

**simulation**
>simulation result: [report](https://www.raidbots.com/simbot/report/akhbaX7GDtJPL4Rpek3Y5m)

![sim](https://media.discordapp.net/attachments/306017089561559040/348533133798539264/Unbenannt.png)

**Comment by Mystler** [comment]
Partially implemented in https://github.com/simulationcraft/simc/commit/04f1c43ab2d39c3fb998338010fa5c345bba56ef. The stealthed condition changes were unnecessary and a loss in AoE. Thank you!
