### ISSUE TITLE
T20 Profile update for netherlight Crucible

### ISSUE THREAD

**Issue by BatFromSpace** [Ravenholdt-TC/Issues#67]
**Game Version:**
>7.3.0

**Description:**
>
New T20M rules allow 24 points in convergence and maxed out netherlight crucible.

artifact=17:0:0:0:0:851:1:852:4:853:4:854:4:855:4:856:4:857:4:858:4:859:4:860:4:861:1:862:1:863:1:864:1:865:1:866:1:1349:1:1386:1:1585:4:1586:1:1587:1:1588:24:1653:1
crucible=1739:3:1771:3:858:3
These should provide the maximum (single-target) DPS increase when added.
Soul Shadows, for AOE viability, would instead be crucible=1739:3:1771:3:857:3

Reports confirming T2 trait:
 https://www.raidbots.com/reports/98kzGihFiVuh6iPSuZmiBw/index.html
Reports confirming relic choice: 
https://www.raidbots.com/reports/2CVUzHQn3z9fqUHZa24VA/index.html

For T20H, 16 points in convergence and T2 netherlight crucible are permitted.
artifact=17:0:0:0:0:851:1:852:4:853:4:854:4:855:4:856:4:857:4:858:4:859:4:860:4:861:1:862:1:863:1:864:1:865:1:866:1:1349:1:1386:1:1585:4:1586:1:1587:1:1588:15:1653:1
crucible=1739:3:1771:3

**Comment by Mystler** [comment]
Thank you for reporting some research on the topic of default profiles. If nobody will implement it first, I intend to do so once I return from my vacation (in about 2d).

**Comment by Mystler** [comment]
Updated the T20 default profiles with crucible traits in https://github.com/simulationcraft/simc/commit/603460c6ed2437d6d6ee238d95b885a6b86e4aff. Thanks!
