### ISSUE TITLE
[APL] Investigate Master Assassin relic value

### ISSUE THREAD

**Issue by Mystler** [Ravenholdt-TC/Issues#68]
Currently, two MA relics sim lower than just one. When I checked it out, I found that issue to be caused by https://github.com/simulationcraft/simc/commit/93b0c77a297d699976418b337afaaad4f7a23959. Reverting that commit is a DPS loss, however.

We should try to get both: good DPS and proper MA relic scaling.

**Comment by aethys256** [comment]
Any kind of delay is not worth (in average at least). I tried to dump energy (with envenom overlapping), but it was not worth.
I removed completely the conditions in https://github.com/simulationcraft/simc/commit/83f1e3e1b13e90e40a1cabcdf0cbe92adf4cd715, it's a gain in all situation.

**Comment by Mystler** [comment]
Looks like this is still not fixed.

**Comment by Mystler** [comment]
Closing for this for BfA.
