### ISSUE TITLE
Outlaw's vanish usage improvment for RTB+SND.

### ISSUE THREAD

**Issue by Saberslashh** [Ravenholdt-TC/Issues#69]
**Description:**
>Vanish is being used weirdly, at 3.4 seconds into the fight for both talents' APL, wasting mantle window.

**Howto:**
>Here is the line to fix it
 `actions.stealth+=/vanish,if=variable.ambush_condition&mantle_duration=0|(equipped.mantle_of_the_master_assassin&mantle_duration=0&!variable.rtb_reroll&!variable.ss_useable)`

**Comment by Mystler** [comment]
Thanks for the report. 👍 Implemented in https://github.com/simulationcraft/simc/commit/d9752363a13224ad9bafec92a2af39a5d02a4854.
