### ISSUE TITLE
[Bugs] Mythic Gul'dan perma Mantle

### ISSUE THREAD

**Issue by aethys256** [Ravenholdt-TC/Issues#7]
**Game Version:**
>7.2.0 Live Build 24015

**Description:**
>(Phase 3) Extends the Mantle buff up to ~10 minutes if you enter the Time stop field while having Vanish buff.

**Reproduce rate:**
>High

**Details:**
>https://us.battle.net/forums/en/wow/topic/20754805626

**Howto:**
>Just use Vanish to proc the Mantle buff before going into the bubble.

**Comment by Mystler** [comment]
Looks like this was fixed in 7.2.5. I could not reproduce it last night.
