### ISSUE TITLE
[APL] Exsanguinate Update

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#70]
**Improvements for Exanguinate:**
> Changes in Opener mainly
> credits to **Infexious#0005**
>
>**APL diff:** [changes](https://www.diffchecker.com/xs2NxV0j)

**simulation**
>simulation result(base profile): [report](https://www.raidbots.com/reports/9nD99GT5tDDAWGiSqsiSe1/index.html)

>![sim](https://media.discordapp.net/attachments/317311523196370954/363625388892749826/image.png)

>with custom gear:
![sim](https://media.discordapp.net/attachments/317311523196370954/363626183256047617/image.png)

**Comment by Mystler** [comment]
Thank you. 👍 Added in https://github.com/simulationcraft/simc/commit/73e10df099760fa2c5d359f5b240a7c553bb6dc5.
