### ISSUE TITLE
[APL] Void-stalkers contract improvement

### ISSUE THREAD

**Issue by Saberslashh** [Ravenholdt-TC/Issues#71]
**Description:**
>The trinket is not used correctly in simC as it's only used during shadowblades/vendetta.
![943da183cc604cd2122f1d47f1e9ab8d](https://user-images.githubusercontent.com/29813274/32328541-8fd0e3d8-bfda-11e7-9d26-32227636c6dd.png)

**Details:**
>It should be used on cd for assassination, during shadow dance so after dfa combo for subtlety and during curse of the dreadblades/vanish for outlaw.

**Howto:**
> 
`use_item,name=void_stalkers_contract,if=(buff.shadow_dance.up)` For subtlety.
`use_item,name=void_stalkers_contract` For assassination.
`use_item,name=void_stalkers_contract,if=(buff.curse_of_the_dreadblades.up|buff.vanish.up)` For outlaw.

**Comment by Mystler** [comment]
Thank you. Improvements for the trinkets have been pushed in https://github.com/simulationcraft/simc/commit/f1b6db95e7b19d11c5d587ddfefbe4b85961f72d.
