### ISSUE TITLE
[APL] Subtlety Symbols improvements

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#72]
**Improvements for Symbols of Death:**
> Change to use symbols on cooldown when talented in MfD.
> It seems to be a win by default, the highest win is with t20 4p + t21 2p.
>
> credits to Eleem#1507.
>**APL diff:** [changes](https://www.diffchecker.com/bkMzD7y7)

**simulation**
>simulation result: [report](https://www.raidbots.com/simbot/report/9iHvDDHK6FcRVucBjUHZhz/simc)
![image](https://media.discordapp.net/attachments/266712108861751296/384346653475340288/image.png)

**Comment by Mystler** [comment]
Thank you. Added in https://github.com/simulationcraft/simc/commit/1db5feaf52db347cbb6b5f4d69f0a001bb230c1a.
