### ISSUE TITLE
[APL] The First of the Dead improvements

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#73]
**Improvements for The First of the Dead:**
> Changed usage to symbols->evi(3+cp)->backstab/vanish+ss
>
>**APL diff:** [changes](https://www.diffchecker.com/2HhzUlXP)

**simulation**
>simulation result: [report](https://www.raidbots.com/simbot/report/4iRHBWYNcJqDdFBrmrrazu/simc)
![image](https://media.discordapp.net/attachments/321995036193456149/385448024043945994/image.png)

**Comment by EvanMichaels** [comment]
Minor note:

> actions+=/call_action_list ... &buff.the_first_of_the_dead.remains>1 ... &equipped.the_first_of_the_dead

Possibly could be simplified since the buff will only ever be present when the hands are equipped? So the equipped check is likely redundant here.

**Comment by Mystler** [comment]
Thank you! Updated in https://github.com/simulationcraft/simc/commit/363ab340946921a7718fae143a044f9332f5c6a3.
