### ISSUE TITLE
[APL] Investigate Forgefiend's Fabricator Conditions

### ISSUE THREAD

**Issue by EvanMichaels** [Ravenholdt-TC/Issues#74]
Currently the default expressions for Forgefiend's Fabricator a very non-optimal, since the only reason for the on-use is to potentially synchronize with cooldowns or AoE waves. 

Just using the same conditionals as Umbral Moonglaives results in ~10k improvement on my character, but it's quite likely there may be some more optimal expressions here considering the 30s duration.

**Comment by Mystler** [comment]
Thank you! Added in https://github.com/simulationcraft/simc/commit/4ac1e5ed537fb13fd71b3c500e0ee2dde92c5f3c.
