### ISSUE TITLE
[Bug] Deadly Poison Snapshots Nightstalker Multiplier

### ISSUE THREAD

**Issue by EvanMichaels** [Ravenholdt-TC/Issues#81]
**Game Version:**
> Live 7.3.2 25549

**Description:**
> When the first ability from stealth applies Deadly Poison with the Nightstalker talent, the 50% persistent multiplier is applied to Deadly Poison as well and can be refreshed indefinitely.

**Reproduce rate:**
> 100% (when setup properly)

**Details:**
> Using Poisoned Knife (preferred) or Fan of Knives (AoE) to apply Deadly Poison to the target(s) out of stealth will cause the triggered Deadly Poison debuff to snapshot the +50% persistent multiplier. There is no way to overwrite this multiplier mid-fight. (e.g. if you do **not** apply from stealth, using Vanish -> Poison will still not overwrite this.) Vanish works to do this mid-fight, provided a Deadly Poison debuff is not already present on the target.

**Howto:**
> Using Poisoned Knife is preferred on ST due to the 100% proc rate on poison, however you must be close to the target as casting Poison Knife breaks stealth and the poison only applies when the projectile lands. Using Shadowstep -> Poisoned Knife appears to be a reliable setup on most enemies tested. Using Poisoned Knife from range will not reliably set up the snapshot, depending on latency. It is also possible latency could impact this setup in general.

**Comment by fuu1** [comment]
Fixed on live as of today.
