### ISSUE TITLE
[Bug] Poisoned Knife Can Apply Poisons Twice

### ISSUE THREAD

**Issue by EvanMichaels** [Ravenholdt-TC/Issues#82]
**Game Version:**
> Live 7.3.2 25549

**Description:**
> Poisoned Knife appears to have a 100% chance to trigger poisons in addition to the normal chance to trigger poisons a second time.

**Reproduce rate:**
> 100%

**Details:**
> Using Poisoned Knife repeatedly shows that it can sometimes refresh its own poison application after casting. When this happens, it results in an additional DD tick as well as the extended duration. Poisoned Knife is likely set up to trigger Deadly Poison on impact, but then inherits the normal weapon-based chance to proc poisons in addition to this.

**Comment by Mystler** [comment]
This has been fixed on Jan 5.
