### ISSUE TITLE
[Wrong Tooltip] Surge of Toxins

### ISSUE THREAD

**Issue by Creixent** [Ravenholdt-TC/Issues#85]
**Game Version:**
>Live

**Description:**
>Surge of Toxins Tooltip "Finishing moves increase Poison damage you deal to the target by 10% for 5 sec." This is wrong. It increases poison damage by %2 per combo point spent up to %10. It caps at %10 even if you have Deeper Stratagem talent.

**Reproduce rate:**
>%100

**Details:**
>As you can see from screenshots here from patch 7.3.5 Deadly poison ticks are consistent with numbers below. 
Base DP x modifier = net value
22038 x 1,02 = 22479 (1 CP)
22038 x 1,04 = 22920 (2 CP)
22038 x 1,06 = 23360 (3 CP)
22038 x 1,08 = 23801 (4 CP)
22038 x 1,10 = 24242 (5 CP)
Link to my screenshots to confirm above numbers  
https://imgur.com/a/EZAHV 

Further AMR (AskMrRobot) also states "This actually gives you 2% poison damage per combo point spent, which is not reflected in the tooltip. It caps out at 10% even with Deeper Stratagem, though." Source https://www.askmrrobot.com/wow/theory/mechanic/spell/surgeoftoxins?spec=RogueAssassination&version=live 

**Howto:**
>Tooltip must be changed to reflect actual buff

**Comment by Lorentz21** [comment]
That is how it is presented in game, nothing we can do. Simc models it correctly https://github.com/simulationcraft/simc/blob/legion-dev/engine/class_modules/sc_rogue.cpp#L6526

**Comment by Creixent** [comment]
OK my bad. This is not the issue on Simc. So I close it.
