### ISSUE TITLE
[BUG] Feint does not reduce Vendetta cooldown with Duskwalker's Footpads

### ISSUE THREAD

**Issue by Notter** [Ravenholdt-TC/Issues#86]
**Game Version:**
7.3.5

**Description:**
And we noticed that feint energy use, does not reduce the cooldown of Vendetta with Duskwalker's Footpads
Unfortunately we can't test this without 7.3.5 now, so i'm not sure if it worked before it.

**Howto:**
The easiest way to test it twice with a stopwatch, once with only using Feint, and another only using Mutilate.
With 3 master assassin relics, mutilate cooldown was shorter by 15-20 seconds.

**Comment by Zolbarr** [comment]
Feint has not reduced the cooldown of Vendetta while equipping Duskwalker's Footpads for the entire expansion.

**Comment by Mystler** [comment]
Closing for this for BfA.
