### ISSUE TITLE
[Bug] Greenskins buff can be consumed with no effect

### ISSUE THREAD

**Issue by Loktark** [Ravenholdt-TC/Issues#88]
**Game Version:**
>7.3.5.25901

**Description:**
>The buff from Greenskin's Waterlogged Wristcuffs is consumed with no effect and no Pistol shot is fired.

**Reproduce rate:**
>100%

**Details:**
>While Greenskin's is up and a Pistol shot cast fails due to a "Target needs to be infront of you" error the cast does not go off but the Greenskin's buff is consumed

**Howto:**
>Get the Greenskin's buff up and cast Pistol shot while facing away from the target.

**Comment by fuu1** [comment]
fixed in  [hotfix jan 26](https://worldofwarcraft.com/en-us/news/21365424)
>**Outlaw**
>Fixed a bug that caused Greenskin's Waterlogged Wristcuffs's to be removed when Pistol Shot failed to cast.
