### ISSUE TITLE
[Bugs] Shadow Gestures (Sub 4-set) - Combo points generation

### ISSUE THREAD

**Issue by MartinLSkoettrup** [Ravenholdt-TC/Issues#89]
**Game Version:**
> 7.3.5.25901

**Description:**
> Subtlety 4-set results in people being unable to generate combo points, after consuming the buff from Stealth.

**Reproduce rate:**
> 100%

**Details:**
> With the 4-set from Subtlety T21 being active and you consuming combo points from stealth, it will result in you being unable to generate combo points again - UNTIL you relog or Hearthstone.

**How to:**
> You get the 4-set proc, leave combat and stealth. From Stealth you then cast either Eviscerate or Nightblade.

**Comment by BatushkaDB** [comment]
From what i've tried so far, it only stops your combo point generation if you had the maximum combo points possible before using this finisher from stealth.
It doesn't stop your generation if you're using Deeper Stratagem and used this finisher with strictly less than 6 combo points.
Hence, switching to Anticipation fixes it.

Edit : gaining atleast one more combo point 'fixes' the bug. It's not the combo point generation that is affected. Getting out of combat, waiting for one combo point to fade away then gaining one combo point works too.

**Comment by fuu1** [comment]
fixed in  [hotfix jan 26](https://worldofwarcraft.com/en-us/news/21365424)
>**Subtlety**
>Fixed a bug that prevented the gain of combo points after consuming the Regalia of the Dashing Scoundrel 4-piece set bonus.
