### ISSUE TITLE
[APL] [Assassination] Improvement on 2-targets fights for Exsanguinate build

### ISSUE THREAD

**Issue by BatushkaDB** [Ravenholdt-TC/Issues#91]
Wondering if i should FoK on 2 targets with Exsanguinate build or not, i've made some tests.

I replaced the following current builder APL section 

actions.build=hemorrhage,if=refreshable
actions.build+=/hemorrhage,cycle_targets=1,if=refreshable&dot.rupture.ticking&spell_targets.fan_of_knives<2+equipped.insignia_of_ravenholdt
actions.build+=/fan_of_knives,if=spell_targets>=2+equipped.insignia_of_ravenholdt|buff.the_dreadlords_deceit.stack>=29
actions.build+=/fan_of_knives,if=variable.use_fok_rotation
actions.build+=/mutilate,cycle_targets=1,if=dot.deadly_poison_dot.refreshable
actions.build+=/mutilate

for this one : 

actions.build=hemorrhage,if=refreshable
actions.build+=/hemorrhage,cycle_targets=1,if=refreshable&dot.rupture.ticking&spell_targets.fan_of_knives<2+equipped.insignia_of_ravenholdt
actions.build+=/fan_of_knives,if=spell_targets>=3|buff.the_dreadlords_deceit.stack>=29
actions.build+=/mutilate,if=debuff.vendetta.up|combo_points<=2
actions.build+=/fan_of_knives,if=spell_targets>=2+equipped.insignia_of_ravenholdt
actions.build+=/fan_of_knives,if=variable.use_fok_rotation
actions.build+=/mutilate,cycle_targets=1,if=dot.deadly_poison_dot.refreshable
actions.build+=/mutilate

It appears to be a gain : 
![exsgnew](https://user-images.githubusercontent.com/35789230/35493032-b3570f4c-04b0-11e8-8e07-066867ab0452.png)

I haven't tried anything for the poison build, nor for 3 targets fights/ There's might also be some improvement possible on this

**Comment by EvanMichaels** [comment]
Thanks for the report, I will try this out on a few other builds as well. Seems like a pretty clear increase for 2T scenarios!

**Comment by EvanMichaels** [comment]
I have integrated this with some modifications into https://github.com/simulationcraft/simc/commit/ebcfcb26074f617519e2a00bc501daeb2355adda

This was a loss for Poison builds so needed to make sure this was Exsang only.
