### ISSUE TITLE
[APL] [Subtlety] Improvement on 2-targets fights for DfA build

### ISSUE THREAD

**Issue by BatushkaDB** [Ravenholdt-TC/Issues#94]
Looking for the reasons why we don't put nightblade on both targets in 2-targets fights, i tried to see what would happen if we did.

I simply deleted the emphasized terms in the following APL line : 

actions.finish+=/nightblade,cycle_targets=1,if=**(!talent.death_from_above.enabled|set_bonus.tier19_2pc)&**(!talent.dark_shadow.enabled|!buff.shadow_dance.up)&target.time_to_die-remains>12&mantle_duration=0&((refreshable&(!finality|buff.finality_nightblade.up|variable.dsh_dfa))|remains<tick_time*2)&(spell_targets.shuriken_storm<4&!variable.dsh_dfa|!buff.symbols_of_death.up)

It appears to be a main target DPS loss, but a DPS gain overall.

![subnew](https://user-images.githubusercontent.com/35789230/35662590-406110e4-0719-11e8-9e10-4d2a2599d53b.png)

This is also a gain for higher numbers of targets, but i think it's possible to do much better than simply multidoting everything for 3+ targets, and maybe for 2 targets.

**Comment by fuu1** [comment]
can confirm that.
It seems to be no win for MfD.
also restricting the use with a shuriken combo condition seems like a slight win
`&(!buff.focused_shurikens.stack<=4&spell_targets.shuriken_storm>=3|spell_targets.shuriken_storm<3)`

**Comment by BatushkaDB** [comment]
Ontop of these previous improvements, prioritizing Backstab over Shuriken Storm during SoD when coming out of ShD is a gain for 2-targets fights (and only for 2-targets fights)

I replaced the Shuriken Storm builder line : 

actions.build=shuriken_storm,if=spell_targets.shuriken_storm>=2+buff.the_first_of_the_dead.up

for this one : 

actions.build=shuriken_storm,if=spell_targets.shuriken_storm>=2+buff.the_first_of_the_dead.up&(spell_targets.shuriken_storm!=2|(spell_targets.shuriken_storm=2&!buff.symbols_of_death.up&!buff.master_of_subtlety.up))

![subnewest](https://user-images.githubusercontent.com/35789230/35707210-27bdf300-07a9-11e8-94e1-dbfebc2e8b86.png)

**Comment by Mystler** [comment]
Thank you for the suggested improvements. I have compiled and added the improvements in https://github.com/simulationcraft/simc/commit/4a4a1240e71ab58a79e9586959c0061852995397.
